zotero:
  user_id: ${oc.env:ZOTERO_ID}
  api_key: ${oc.env:ZOTERO_KEY}
  include_path:
    - "世界模型-土的本构"
    - "世界模型-土的本构/**"
    - "土的本构学习论文"
    - "土的本构学习论文/**"

email:
  sender: ${oc.env:SENDER}
  receiver: ${oc.env:RECEIVER}
  smtp_server: smtp.163.com
  smtp_port: 465
  sender_password: ${oc.env:SENDER_PASSWORD}

llm:
  api:
    key: ${oc.env:OPENAI_API_KEY}
    base_url: ${oc.env:OPENAI_API_BASE}
  api_mode: chat_completion
  generation_kwargs:
    model: Qwen/Qwen3.6-35B-A3B

source:
  arxiv:
    category: ["cs.AI", "cs.LG", "cs.RO", "cs.CE", "stat.ML", "eess.SY", "cond-mat.soft", "physics.geo-ph"]
    include_cross_list: true

executor:
  debug: ${oc.env:DEBUG,null}
  source: ['arxiv']
  max_paper_num: 15
